apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
        - name: flask-api
          image: dfernscap4/flask-api:f53fcbc31fb25f86eddf58c89ad957e534e90ca7
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          env:
            - name: MY_SECRET
              valueFrom:
                secretKeyRef:
                 name: my-secret
                 key: MY_SECRET
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 50m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flask-api
spec:
  type: LoadBalancer
  selector:
    app: flask-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
