---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    MY_SECRET: AgBHB0gpfMtN4uJLfK0FS5zDEwLGw5lbRMlw1VesiJ5xkN1fxbbxHt6nFdupxsnsOZkeTB4c2xsV6476pdIV9LicHq5q7VhuzC4t1dVd1JPHyFn8ZUkHXJd02fCLMhqMreC/UHHgfDotxp2zboZT3rFSyxyCtes5YMidnW8W2EAsCu0ADuUgGw8VvHpuxTxlZBSQSDhU4Fp3cp6iJYX3ODAKV6XjFRC7tK/xv2+kvmpYuu0dE1B2423srm/V2XLySypZ5ChkqNY6l7/eEER625QXEhzkq1iJepoGR23KfWNtYzl18cT7MmVTFbNMKCpp9oxC7wyPTFFYFxI6iUCpYBFydkI+7Grc2A2wqzUar1JxTHFGH0ngzHK21pQZZq8THSuW1j+U9Ctfq7JP9OFlFLld/1KZUuWFRtGoUha/x8+7eDFg1oeEFeVUQ3A6zl7CYeSy6DW7RJxRsqdQFWBklhla4Mm5zGCIwvo6cRRXInxqrHVO8pQigjXH8IpuXpFCuwSsrSUcP64UR/zIeF4mYqAEunHpUUGUbvE2X2bFtAHoay9gGWLAQ21TH/3vVJlSooDteG8WRqwfBQSTKdbcxYQIwvSgFK+4ytHHB0uHXF7Tp0N8cTY15gNjA4wPcVqww7NIUeJQvgtnpdahblTRdXnV70tKYzogQwrQ6eJ7cwen/Oe4kE7XsLEVXzvaJU1RasmMZP9nFziLFEfB7n41
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
